version: '3.9'

services:
  overlay-chat-dev:
    image: node:21-alpine
    container_name: overlay-chat-dev
    profiles: ['dev']
    command: npm run start
    working_dir: /app
    ports:
      - 5173:5173
    volumes:
      - .:/app

  overlay-chat-build:
    image: node:21-alpine
    container_name: overlay-chat-build
    profiles: ['build']
    command: npm run build
    working_dir: /app
    user: '1000'
    volumes:
      - .:/app
